### ISSUE TITLE
Where is the tech data of coin? ))

### ISSUE THREAD

**Issue by mrantonion** [whatcoin-project/whatcoin-old#5]
It's very strange to run a project but give no tech info about the coin.
i.e. what is the total supply of the coin?

**Comment by patro999** [comment]
Looks like only coin team members are mining. Rug Pull scheme?

**Comment by LOUD-Mining** [comment]
The original developers left the project. Deleted EVERYTHING and I am currently trying to clean up this mess. Please stay tuned...

**Comment by BlackPeter13** [comment]
New start planned
